// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: protos/vlan.proto

package vlan

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_OK  State = 0
	State_NOK State = 1
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "OK",
		1: "NOK",
	}
	State_value = map[string]int32{
		"OK":  0,
		"NOK": 1,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_vlan_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_protos_vlan_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_protos_vlan_proto_rawDescGZIP(), []int{0}
}

type VLAN struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vlan string `protobuf:"bytes,2,opt,name=vlan,proto3" json:"vlan,omitempty"`
}

func (x *VLAN) Reset() {
	*x = VLAN{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vlan_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VLAN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VLAN) ProtoMessage() {}

func (x *VLAN) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vlan_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VLAN.ProtoReflect.Descriptor instead.
func (*VLAN) Descriptor() ([]byte, []int) {
	return file_protos_vlan_proto_rawDescGZIP(), []int{0}
}

func (x *VLAN) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VLAN) GetVlan() string {
	if x != nil {
		return x.Vlan
	}
	return ""
}

type SaveVLANResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State State `protobuf:"varint,1,opt,name=state,proto3,enum=vlan.State" json:"state,omitempty"`
}

func (x *SaveVLANResponse) Reset() {
	*x = SaveVLANResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vlan_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveVLANResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveVLANResponse) ProtoMessage() {}

func (x *SaveVLANResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vlan_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveVLANResponse.ProtoReflect.Descriptor instead.
func (*SaveVLANResponse) Descriptor() ([]byte, []int) {
	return file_protos_vlan_proto_rawDescGZIP(), []int{1}
}

func (x *SaveVLANResponse) GetState() State {
	if x != nil {
		return x.State
	}
	return State_OK
}

type GetVLANsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vlans []*VLAN `protobuf:"bytes,1,rep,name=vlans,proto3" json:"vlans,omitempty"`
}

func (x *GetVLANsResponse) Reset() {
	*x = GetVLANsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vlan_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVLANsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVLANsResponse) ProtoMessage() {}

func (x *GetVLANsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vlan_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVLANsResponse.ProtoReflect.Descriptor instead.
func (*GetVLANsResponse) Descriptor() ([]byte, []int) {
	return file_protos_vlan_proto_rawDescGZIP(), []int{2}
}

func (x *GetVLANsResponse) GetVlans() []*VLAN {
	if x != nil {
		return x.Vlans
	}
	return nil
}

var File_protos_vlan_proto protoreflect.FileDescriptor

var file_protos_vlan_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x6c, 0x61, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x76, 0x6c, 0x61, 0x6e, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x04, 0x56, 0x4c, 0x41, 0x4e, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x76, 0x6c, 0x61, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x6c,
	0x61, 0x6e, 0x22, 0x35, 0x0a, 0x10, 0x53, 0x61, 0x76, 0x65, 0x56, 0x4c, 0x41, 0x4e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x76, 0x6c, 0x61, 0x6e, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x34, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x56, 0x4c, 0x41, 0x4e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a,
	0x05, 0x76, 0x6c, 0x61, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x76,
	0x6c, 0x61, 0x6e, 0x2e, 0x56, 0x4c, 0x41, 0x4e, 0x52, 0x05, 0x76, 0x6c, 0x61, 0x6e, 0x73, 0x2a,
	0x18, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x4e, 0x4f, 0x4b, 0x10, 0x01, 0x32, 0x74, 0x0a, 0x02, 0x56, 0x31, 0x12,
	0x30, 0x0a, 0x08, 0x53, 0x61, 0x76, 0x65, 0x56, 0x4c, 0x41, 0x4e, 0x12, 0x0a, 0x2e, 0x76, 0x6c,
	0x61, 0x6e, 0x2e, 0x56, 0x4c, 0x41, 0x4e, 0x1a, 0x16, 0x2e, 0x76, 0x6c, 0x61, 0x6e, 0x2e, 0x53,
	0x61, 0x76, 0x65, 0x56, 0x4c, 0x41, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x3c, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x56, 0x4c, 0x41, 0x4e, 0x73, 0x12, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x76, 0x6c, 0x61, 0x6e, 0x2e, 0x47, 0x65, 0x74,
	0x56, 0x4c, 0x41, 0x4e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x76, 0x6c, 0x61, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protos_vlan_proto_rawDescOnce sync.Once
	file_protos_vlan_proto_rawDescData = file_protos_vlan_proto_rawDesc
)

func file_protos_vlan_proto_rawDescGZIP() []byte {
	file_protos_vlan_proto_rawDescOnce.Do(func() {
		file_protos_vlan_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_vlan_proto_rawDescData)
	})
	return file_protos_vlan_proto_rawDescData
}

var file_protos_vlan_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_vlan_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_vlan_proto_goTypes = []interface{}{
	(State)(0),               // 0: vlan.State
	(*VLAN)(nil),             // 1: vlan.VLAN
	(*SaveVLANResponse)(nil), // 2: vlan.SaveVLANResponse
	(*GetVLANsResponse)(nil), // 3: vlan.GetVLANsResponse
	(*emptypb.Empty)(nil),    // 4: google.protobuf.Empty
}
var file_protos_vlan_proto_depIdxs = []int32{
	0, // 0: vlan.SaveVLANResponse.state:type_name -> vlan.State
	1, // 1: vlan.GetVLANsResponse.vlans:type_name -> vlan.VLAN
	1, // 2: vlan.V1.SaveVLAN:input_type -> vlan.VLAN
	4, // 3: vlan.V1.GetVLANs:input_type -> google.protobuf.Empty
	2, // 4: vlan.V1.SaveVLAN:output_type -> vlan.SaveVLANResponse
	3, // 5: vlan.V1.GetVLANs:output_type -> vlan.GetVLANsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_vlan_proto_init() }
func file_protos_vlan_proto_init() {
	if File_protos_vlan_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_vlan_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VLAN); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vlan_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveVLANResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vlan_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVLANsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_vlan_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_vlan_proto_goTypes,
		DependencyIndexes: file_protos_vlan_proto_depIdxs,
		EnumInfos:         file_protos_vlan_proto_enumTypes,
		MessageInfos:      file_protos_vlan_proto_msgTypes,
	}.Build()
	File_protos_vlan_proto = out.File
	file_protos_vlan_proto_rawDesc = nil
	file_protos_vlan_proto_goTypes = nil
	file_protos_vlan_proto_depIdxs = nil
}
