// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.3
// source: protos/vlan.proto

package vlan

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VLAN struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vlan string `protobuf:"bytes,2,opt,name=vlan,proto3" json:"vlan,omitempty"`
}

func (x *VLAN) Reset() {
	*x = VLAN{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vlan_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VLAN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VLAN) ProtoMessage() {}

func (x *VLAN) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vlan_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VLAN.ProtoReflect.Descriptor instead.
func (*VLAN) Descriptor() ([]byte, []int) {
	return file_protos_vlan_proto_rawDescGZIP(), []int{0}
}

func (x *VLAN) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VLAN) GetVlan() string {
	if x != nil {
		return x.Vlan
	}
	return ""
}

// Get VLAN
type SaveVLANRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vlan *VLAN `protobuf:"bytes,1,opt,name=vlan,proto3" json:"vlan,omitempty"`
}

func (x *SaveVLANRequest) Reset() {
	*x = SaveVLANRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vlan_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveVLANRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveVLANRequest) ProtoMessage() {}

func (x *SaveVLANRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vlan_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveVLANRequest.ProtoReflect.Descriptor instead.
func (*SaveVLANRequest) Descriptor() ([]byte, []int) {
	return file_protos_vlan_proto_rawDescGZIP(), []int{1}
}

func (x *SaveVLANRequest) GetVlan() *VLAN {
	if x != nil {
		return x.Vlan
	}
	return nil
}

type SaveVLANResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaveVLANResponse) Reset() {
	*x = SaveVLANResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vlan_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveVLANResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveVLANResponse) ProtoMessage() {}

func (x *SaveVLANResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vlan_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveVLANResponse.ProtoReflect.Descriptor instead.
func (*SaveVLANResponse) Descriptor() ([]byte, []int) {
	return file_protos_vlan_proto_rawDescGZIP(), []int{2}
}

// Get VLANs
type GetVLANsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetVLANsRequest) Reset() {
	*x = GetVLANsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vlan_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVLANsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVLANsRequest) ProtoMessage() {}

func (x *GetVLANsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vlan_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVLANsRequest.ProtoReflect.Descriptor instead.
func (*GetVLANsRequest) Descriptor() ([]byte, []int) {
	return file_protos_vlan_proto_rawDescGZIP(), []int{3}
}

type GetVLANsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vlans []*VLAN `protobuf:"bytes,1,rep,name=vlans,proto3" json:"vlans,omitempty"`
}

func (x *GetVLANsResponse) Reset() {
	*x = GetVLANsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vlan_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVLANsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVLANsResponse) ProtoMessage() {}

func (x *GetVLANsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vlan_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVLANsResponse.ProtoReflect.Descriptor instead.
func (*GetVLANsResponse) Descriptor() ([]byte, []int) {
	return file_protos_vlan_proto_rawDescGZIP(), []int{4}
}

func (x *GetVLANsResponse) GetVlans() []*VLAN {
	if x != nil {
		return x.Vlans
	}
	return nil
}

// Get VLAN
type GetVLANRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetVLANRequest) Reset() {
	*x = GetVLANRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vlan_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVLANRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVLANRequest) ProtoMessage() {}

func (x *GetVLANRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vlan_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVLANRequest.ProtoReflect.Descriptor instead.
func (*GetVLANRequest) Descriptor() ([]byte, []int) {
	return file_protos_vlan_proto_rawDescGZIP(), []int{5}
}

func (x *GetVLANRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetVLANResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vlan *VLAN `protobuf:"bytes,1,opt,name=vlan,proto3" json:"vlan,omitempty"`
}

func (x *GetVLANResponse) Reset() {
	*x = GetVLANResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vlan_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVLANResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVLANResponse) ProtoMessage() {}

func (x *GetVLANResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vlan_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVLANResponse.ProtoReflect.Descriptor instead.
func (*GetVLANResponse) Descriptor() ([]byte, []int) {
	return file_protos_vlan_proto_rawDescGZIP(), []int{6}
}

func (x *GetVLANResponse) GetVlan() *VLAN {
	if x != nil {
		return x.Vlan
	}
	return nil
}

var File_protos_vlan_proto protoreflect.FileDescriptor

var file_protos_vlan_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x6c, 0x61, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x76, 0x6c, 0x61, 0x6e, 0x22, 0x2a, 0x0a, 0x04, 0x56, 0x4c, 0x41,
	0x4e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x6c, 0x61, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x76, 0x6c, 0x61, 0x6e, 0x22, 0x31, 0x0a, 0x0f, 0x53, 0x61, 0x76, 0x65, 0x56, 0x4c, 0x41,
	0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x76, 0x6c, 0x61, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x76, 0x6c, 0x61, 0x6e, 0x2e, 0x56, 0x4c,
	0x41, 0x4e, 0x52, 0x04, 0x76, 0x6c, 0x61, 0x6e, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x61, 0x76, 0x65,
	0x56, 0x4c, 0x41, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x56, 0x4c, 0x41, 0x4e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x34, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x56, 0x4c, 0x41, 0x4e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x76, 0x6c, 0x61, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x76, 0x6c, 0x61, 0x6e, 0x2e, 0x56, 0x4c, 0x41, 0x4e, 0x52, 0x05,
	0x76, 0x6c, 0x61, 0x6e, 0x73, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x56, 0x4c, 0x41, 0x4e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x31, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x56, 0x4c,
	0x41, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x76, 0x6c,
	0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x76, 0x6c, 0x61, 0x6e, 0x2e,
	0x56, 0x4c, 0x41, 0x4e, 0x52, 0x04, 0x76, 0x6c, 0x61, 0x6e, 0x32, 0xb8, 0x01, 0x0a, 0x02, 0x56,
	0x31, 0x12, 0x3b, 0x0a, 0x08, 0x53, 0x61, 0x76, 0x65, 0x56, 0x4c, 0x41, 0x4e, 0x12, 0x15, 0x2e,
	0x76, 0x6c, 0x61, 0x6e, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x56, 0x4c, 0x41, 0x4e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x76, 0x6c, 0x61, 0x6e, 0x2e, 0x53, 0x61, 0x76, 0x65,
	0x56, 0x4c, 0x41, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b,
	0x0a, 0x08, 0x47, 0x65, 0x74, 0x56, 0x4c, 0x41, 0x4e, 0x73, 0x12, 0x15, 0x2e, 0x76, 0x6c, 0x61,
	0x6e, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x4c, 0x41, 0x4e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x76, 0x6c, 0x61, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x4c, 0x41, 0x4e,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x07, 0x47,
	0x65, 0x74, 0x56, 0x4c, 0x41, 0x4e, 0x12, 0x14, 0x2e, 0x76, 0x6c, 0x61, 0x6e, 0x2e, 0x47, 0x65,
	0x74, 0x56, 0x4c, 0x41, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x76,
	0x6c, 0x61, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x4c, 0x41, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x76, 0x6c, 0x61, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_vlan_proto_rawDescOnce sync.Once
	file_protos_vlan_proto_rawDescData = file_protos_vlan_proto_rawDesc
)

func file_protos_vlan_proto_rawDescGZIP() []byte {
	file_protos_vlan_proto_rawDescOnce.Do(func() {
		file_protos_vlan_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_vlan_proto_rawDescData)
	})
	return file_protos_vlan_proto_rawDescData
}

var file_protos_vlan_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protos_vlan_proto_goTypes = []interface{}{
	(*VLAN)(nil),             // 0: vlan.VLAN
	(*SaveVLANRequest)(nil),  // 1: vlan.SaveVLANRequest
	(*SaveVLANResponse)(nil), // 2: vlan.SaveVLANResponse
	(*GetVLANsRequest)(nil),  // 3: vlan.GetVLANsRequest
	(*GetVLANsResponse)(nil), // 4: vlan.GetVLANsResponse
	(*GetVLANRequest)(nil),   // 5: vlan.GetVLANRequest
	(*GetVLANResponse)(nil),  // 6: vlan.GetVLANResponse
}
var file_protos_vlan_proto_depIdxs = []int32{
	0, // 0: vlan.SaveVLANRequest.vlan:type_name -> vlan.VLAN
	0, // 1: vlan.GetVLANsResponse.vlans:type_name -> vlan.VLAN
	0, // 2: vlan.GetVLANResponse.vlan:type_name -> vlan.VLAN
	1, // 3: vlan.V1.SaveVLAN:input_type -> vlan.SaveVLANRequest
	3, // 4: vlan.V1.GetVLANs:input_type -> vlan.GetVLANsRequest
	5, // 5: vlan.V1.GetVLAN:input_type -> vlan.GetVLANRequest
	2, // 6: vlan.V1.SaveVLAN:output_type -> vlan.SaveVLANResponse
	4, // 7: vlan.V1.GetVLANs:output_type -> vlan.GetVLANsResponse
	6, // 8: vlan.V1.GetVLAN:output_type -> vlan.GetVLANResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_vlan_proto_init() }
func file_protos_vlan_proto_init() {
	if File_protos_vlan_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_vlan_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VLAN); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vlan_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveVLANRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vlan_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveVLANResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vlan_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVLANsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vlan_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVLANsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vlan_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVLANRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vlan_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVLANResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_vlan_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_vlan_proto_goTypes,
		DependencyIndexes: file_protos_vlan_proto_depIdxs,
		MessageInfos:      file_protos_vlan_proto_msgTypes,
	}.Build()
	File_protos_vlan_proto = out.File
	file_protos_vlan_proto_rawDesc = nil
	file_protos_vlan_proto_goTypes = nil
	file_protos_vlan_proto_depIdxs = nil
}
